lib/myApp_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :login_required do
    
  end

  pipeline :admin_required do
    
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug MyAppWeb.CurrentUser
  end

  scope "/", MyAppWeb do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:show, :new, :create]
  
    scope "/" do
      pipe_through [:login_required]
      resources "/users", UserController, only: [:show] do
        resources "/posts", PostController
      end
  
      # admin zone
      scope "/admin", Admin, as: :admin do
        pipe_through [:admin_required]
        resources "/users", UserController, only: [:index, :show] do
          resources "/posts", PostController, only: [:index, :show]
        end
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyAppWeb do
  #   pipe_through :api
  # end
end

lib/myApp/application.ex
defmodule MyApp.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(MyApp.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MyAppWeb.Endpoint, []),
      
      supervisor(MyAppWeb.Presence, []),

      # supervisor(MyApp.Presence, []),
      # Start your own worker by calling: MyApp.Worker.start_link(arg1, arg2, arg3)
      # worker(MyApp.Worker, [arg1, arg2, arg3]),

    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MyAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/myApp/post.ex
defmodule MyApp.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias MyApp.Post


  schema "posts" do
    field :message, :string
    field :user_id, :id

    

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:message])
    |> validate_required([:message])
    |> assoc_constraint(:user)
  end
end

lib/myApp/repo.ex
defmodule MyApp.Repo do
  use Ecto.Repo, otp_app: :myApp

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/myApp/user.ex
defmodule MyApp.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias MyApp.User


  schema "users" do
    field :bio, :string
    field :email, :string
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    field :is_admin, :boolean, default: false, null: false

    has_many :posts, MyApp.Post

    timestamps()
  end

  @doc false
  def changeset(struct, attrs \\ %{}) do
    struct
    |> cast(attrs, [:name, :email, :bio])
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
  end

  def registration_changeset(struct, params) do
    struct
    |> changeset(params)
    |> cast(params, ~w(password)a, [])
    |> validate_length(:password, min: 6, max: 100)
    |> hash_password
  end


  defp hash_password(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true,
                      changes: %{password: password}} ->
        put_change(changeset,
                   :password_hash,
                   Comeonin.Bcrypt.hashpwsalt(password))
      _ ->
        changeset
    end
  end


end

web/models/post.ex
defmodule MyApp.Post do
  use MyApp.Web, :model

  schema "posts" do
    field :message, :string
    belongs_to :user, MyApp.User, foreign_key: :user_id

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:message])
    |> validate_required([:message])
  end
end

lib/myApp_web/controllers/page_controller.ex
defmodule MyAppWeb.PageController do
  use MyAppWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/myApp_web/views/error_view.ex
defmodule MyAppWeb.ErrorView do
  use MyAppWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/myApp_web/views/layout_view.ex
defmodule MyAppWeb.LayoutView do
  use MyAppWeb, :view
end

lib/myApp_web/views/page_view.ex
defmodule MyAppWeb.PageView do
  use MyAppWeb, :view
end

lib/myApp_web/views/post_view.ex
defmodule MyApp.PostView do
    use MyAppWeb, :view
end
  

lib/myApp_web/views/session_view.ex
defmodule MyAppWeb.SessionView do
    use MyAppWeb, :view
  end

lib/myApp_web/views/user_view.ex
defmodule MyAppWeb.UserView do
    use MyAppWeb, :view
end

lib/myApp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello MyApp!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
  <%= if @current_user do %>
    <li><%= @current_user.email %> (<%= @current_user.id %>)</li>
    <li>
      <%= link "Sign out", to: session_path(@conn, :delete,
                                            @current_user),
                           method: "delete" %>
    </li>
  <% else %>
    <li><%= link "Register", to: user_path(@conn, :new) %></li>
    <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
  <% end %>
</ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/myApp_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row">
  <div class="col-md-12">
    <span id="user">Welcome <%= @conn.params["name"] %></span>
  </div>
  <div class="col-md-8">
    <h3>Messages:</h3>
    <ul id="message-list" class="list-unstyled">

    </ul>

    <input type="text" id="new-message" class="form-control">
  </div>
  <div class="col-md-4">
    <h3>Users Online:</h3>
    <ul id="user-list" class="list-unstyled">

    </ul>
  </div>
</div>

lib/myApp_web/templates/post/edit.html.eex
# web/templates/post/edit.html.eex
<h1>Edit post</h1>
<%= form_for @changeset, user_post_path(@conn, :update, @current_user,
                                        @post), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There are some errors</p>
    </div>
  <% end %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <div class="form-group">
    <%= textarea f, :body, placeholder: "Body", class: "form-control" %>
    <%= error_tag f, :body %>
  </div>
  <span>
    <%= submit "Edit", class: "btn btn-primary" %>
    &nbsp;
    <%= link "Cancel", to: user_post_path(@conn, :show, @current_user, 
                                          @post) %>
  </span>
<% end %>

lib/myApp_web/templates/post/index.html.eex
<%= if @current_user.id == @user.id do %>
    <h1>My Posts</h1>
    <%= link "Create new", to: user_post_path(@conn, :new, 
                                              @current_user) %>
  <% else %>
    <h1><%= @user.name %>s Posts</h1>
  <% end %>
  <ul>
    <%= for post <- @posts do %>
      <li>
        <%= link post.title, to: user_post_path(@conn, :show, 
                                                post.user, post) %>
      </li>
    <% end %>
  </ul>

lib/myApp_web/templates/post/new.html.eex
# web/templates/post/new.html.eex
<h1>Create Post</h1>
<%= form_for @changeset, user_post_path(@conn, :create, @current_user),
                                                        fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There are some errors</p>
    </div>
  <% end %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title",
                              class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <div class="form-group">
    <%= textarea f, :body, placeholder: "Body", class: "form-control" %>
    <%= error_tag f, :body %>
  </div>
  <%= submit "Create post", class: "btn btn-primary" %>
<% end %>

lib/myApp_web/templates/post/show.html.eex
  # web/templates/post/show.html.eex
  <%= link "To list", to: user_post_path(@conn, :index, @post.user) %>
  <h1><%= @post.title %></h1>
  <p><%= @post.body %></p>
  <%= if @current_user.id == @user.id do %>
    <span>
      <%= link "Edit", to: user_post_path(@conn, :edit, @current_user, 
                       @post), class: "btn btn-primary btn-xs" %>
      &nbsp;
      <%= link "Delete", to: user_post_path(@conn, :delete, 
                         @current_user, @post),
                         method: :delete,
                         data: [confirm: "Really?"],
                         class: "btn btn-danger btn-xs"%>
    </span>
  <% end %>

lib/myApp_web/templates/session/new.html.eex
<h1>Sign in</h1>
<%= form_for @conn, session_path(@conn, :create),
                                          [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email",
                              class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password",
                                     class: "form-control" %>
  </div>
  <%= submit "Sign in", class: "btn btn-primary" %>
<% end %>

lib/myApp_web/templates/user/new.html.eex
<h1>User Registration</h1>
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>There are some errors</p>
    </div>
  <% end %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email",
                              class: "fbelongs_to :user, MyApp.Userorm-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name",
                             class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password",
                                     class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

lib/myApp_web/templates/user/show.html.eex
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>